image: lorisleiva/laravel-docker:8.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

composer:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    expire_in: 1 day
    paths:
      - vendor/
      - .env

npm:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  script:
    - npm install
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules/
      - public/css/
      - public/js/

codestyle:
  stage: test
  cache: {}
  script:
    - phpcs --standard=PSR2 --extensions=php app

phpunit:
  stage: test
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
    - XDEBUG_MODE=coverage phpunit --coverage-text --colors=never
